services:
  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "4500:4500"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    image: php:7.4-apache
    container_name: php_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Senha123
      - DB_NAME=meubanco
    volumes:
      - ./php:/var/www/html
    command: ["apache2-foreground"]

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




